### ISSUE TITLE
Configurable delay time?

### ISSUE THREAD

**Issue by BobbyWibowo** [freneticfeline/mod_autofish#4]
Is there any plan to add configurable delay time or something like that? Something like waiting for 2 seconds before re-casting the rod. This will be pretty helpful in SMP when your ping isn't stable.
Sometimes there'll be delays before your casting "state" be applied to the server and the mod will end up failing because then your state will forcibly be set to "not casting" (instead of naturally reeling in - so the mod will end up not noticing that you have stopped fishing without the player's intention).

**UPDATE:** I'll be using the original mod for now. It has an option to re-cast when hook entity is cleared, which I assume is a workaround for the issue that I'm having.

**Comment by freneticfeline** [comment]
@BobbyWibowo The entity clear option is for the case when the server periodically issues a command to clear all entities from the world, which seems to be common practice on worlds with many players.  The 1.12 version of mod_autofish includes this option as an experimental feature, and I plan to port it back to previous versions of the mod, but I do not believe it will help with your issue.  I am investigating a configurable delay time as you suggested.

**Comment by BobbyWibowo** [comment]
Hummu, I see. Oh well, I haven't gotten the chance to test that version out more deeply to be honest, so I don't know if it will actually help or not. It only happened when my internet was at its worst after all, but alright, thanks!

**Comment by freneticfeline** [comment]
@BobbyWibowo What version of Minecraft are you concerned about?  I have added the configurable re-cast delay to the mod for 1.12, and back-ported it to the 1.11/1.11.2 version.  I am currently working on back-porting it to the 1.10/1.10.2 version.  1.9 and 1.8 versions will come next, time permitting.

**Comment by BobbyWibowo** [comment]
I would originally be completely satisfied with 1.11.2 since the modpack I was playing on was on that veresion. But due to various circumstances, we're now using 1.10.2, so compatibility for that version would be best. Thanks in advance.

**Comment by freneticfeline** [comment]
The option has been ported back to 1.9.x.
