### ISSUE TITLE
This doesn't work for MC v1.13.2

### ISSUE THREAD

**Issue by 8MiYile** [freneticfeline/mod_autofish#7]
Please Update To Minecraft v1.13.2, Thank You, Sir

**Comment by 8MiYile** [comment]
Minecraft Forge is Releaese Beta Version,So can you releaese autofish for Minecraft v1.13.2?

**Comment by freneticfeline** [comment]
Unfortunately, Forge Beta Version currently has some bugs involving fishing rods that is preventing me from updating the mod.

**Comment by Diluka** [comment]
crashed in mc `1.14.4` forge `28.0.45` too

**Comment by freneticfeline** [comment]
Release posted for 1.13.x.  Please note that Forge 1.13 never progressed past Beta release, so this mod should also be considered Beta.
