### ISSUE TITLE
Help modifying something :3

### ISSUE THREAD

**Issue by hegzploit** [freneticfeline/mod_autofish#8]
Hey,
I'm trying to make it cast the rod from water/stop fishing, when a certain string is matched in chat.
I thought i would edit the Clear Entity function so it stops fishing when it sees my "certain string in chat" but it seems that it doesn't work like that.
can you help me with this.

**Comment by freneticfeline** [comment]
No, the Clear Entity feature doesn't work based on chat.  I have never done anything with chat, so I don't think I can help you.
