### ISSUE TITLE
Minecraft forge 1.15 support

### ISSUE THREAD

**Issue by mgjuhler** [freneticfeline/mod_autofish#9]
Hi, 
Will this be updated for minecraft forge 1.15 ?

**Comment by freneticfeline** [comment]
I plan to update it for 1.15.  However, the Forge team just released a 1.15 Beta release today.  There will not be an official release of the mod until there is a stable "recommended" Forge 1.15 release, which may take a while.  There may be an unofficial 1.15 release before then if the Forge beta reaches a stable state.
